## Social Networking Ads Data

In [113]:
import numpy as np
import pandas as pd

In [114]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [115]:
df = pd.read_csv("Social_Network_Ads - Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [116]:
df = df.drop(columns= ['User ID', 'Gender'])

x = df.drop(columns= ['Purchased'])
y = df['Purchased']

In [117]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

In [118]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [119]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [120]:
y_pred = pipe.predict(x_test)

In [121]:
acc = accuracy_score(y_test, y_pred)
acc

0.8875

## Covid Toy Dataset

In [122]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [123]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [124]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
cat_columns = [col for col in df.columns if df[col].dtypes == 'str']
cat_columns

['gender', 'cough', 'city', 'has_covid']

In [125]:
for col in cat_columns:
    df[col] = lb.fit_transform(df[col])

df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [126]:
x = df.drop(columns= ['has_covid'])
y = df['has_covid']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [127]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('classifier', LogisticRegression())
])

In [128]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', LogisticRegression())])

In [129]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', LogisticRegression())])

In [130]:
y_pred = pipe.predict(x_test)

In [131]:
score = accuracy_score(y_test, y_pred)
score

0.7